xen/x86: unbreak intel build
Commit 391fb645e467 causes build breakages when INTEL is enabled:

power.c:(.text.unlikely.enter_state_helper+0x93): undefined reference to `cpufreq_del_cpu'
power.c:(.text.unlikely.enter_state_helper+0x93): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `cpufreq_del_cpu'
x86_64-linux-gnu-ld: power.c:(.text.unlikely.enter_state_helper+0x25f): undefined reference to `cpufreq_add_cpu'
power.c:(.text.unlikely.enter_state_helper+0x25f): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `cpufreq_add_cpu'
x86_64-linux-gnu-ld: prelink.o: in function `intel_thermal_interrupt':
mce_intel.c:(.text.intel_thermal_interrupt+0x28): undefined reference to `hwp_active'
mce_intel.c:(.text.intel_thermal_interrupt+0x28): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `hwp_active'
x86_64-linux-gnu-ld: ./.xen-syms.0: hidden symbol `hwp_active' isn't defined
x86_64-linux-gnu-ld: final link failed: bad value

As a solution, as we are not trying to optimize the INTEL build, simply
add "select CPUFREQ" to the INTEL config option.

Signed-off-by: Stefano Stabellini <stefano.stabellini@amd.com>
Reviewed-by: Michal Orzel <michal.orzel@amd.com>