xen/coverage: Fix pointer-to-paddr_t cast in printk
The coverage_collect() debug printk casts a char pointer to paddr_t to
print its address. On ARM32, pointers are 32-bit but paddr_t can be
64-bit, causing a -Werror=pointer-to-int-cast error.

Use %p to print the virtual address, which is portable and correct.

Fixes ARM32 build error:
  error: cast from pointer to integer of different size

Signed-off-by: Stefano Stabellini <stefano.stabellini@amd.com>
Reviewed-by: Michal Orzel <michal.orzel@amd.com>