tools + xen: Inform toolstack about XEN_SYSCTL_PHYSCAP_nestedhvm
xenctrl_abi_check.h: In function 'c_bitmap_to_ocaml_list':
/builds/xen-project/people/amd/xen/tools/ocaml/libs/xc/../../../../tools/include/xen-tools/common-macros.h:15:28: error: static assertion failed: "!(XEN_SYSCTL_PHYSCAP_MAX != (1u << 9))"
   15 | #define BUILD_BUG_ON(p) ({ _Static_assert(!(p), "!(" #p ")"); })
      |                            ^~~~~~~~~~~~~~
xenctrl_abi_check.h:44:1: note: in expansion of macro 'BUILD_BUG_ON'
   44 | BUILD_BUG_ON( XEN_SYSCTL_PHYSCAP_MAX         != (1u << 9)  );
      | ^~~~~~~~~~~~

Take the opportunity to fix the NESTED_VIRT Kconfig option to default y
and unset it in the safety defconfig (recreate the proper order using
savedefconfig).

Fixes: 3348d1b70e00 ("x86/hvm: Add Kconfig option to disable nested virtualization")
Signed-off-by: Michal Orzel <michal.orzel@amd.com>
Reviewed-by: Ayan Kumar Halder <ayan.kumar.halder@amd.com>