WA to avoid linkage error
Due to some unclear reason having thunderx.o lead to xen/arch/arm/builtin.o
linkage failed during xen/arch/arm/platform/builtin.o parsing with errors like

Error: L6242E: Cannot link object built_in.o as its attributes are incompatible with the image attributes.
   ... A64 clashes with SoftVFP.
Error: L6242E: Cannot link object built_in.o as its attributes are incompatible with the image attributes.
   ... A64 clashes with SoftVFP.
Error: L6242E: Cannot link object built_in.o as its attributes are incompatible with the image attributes.
   ... A64 clashes with SoftVFP.
Error: L6242E: Cannot link object built_in.o as its attributes are incompatible with the image attributes.
   ... A64 clashes with SoftVFP.