xen/x86: Split .ex_table sections
Use SECTNAME() and REF() to split .ex_table and associate them with
their users.

The assembly version of _ASM_EXTABLE now calls an ASSEMBLY macro so that
\@ can be used in for unique labels.

Include a leading space before REF to avoid:
./arch/x86/include/asm/msr.h:102: Error: unknown pseudo-op: `.previous.reloc'

Order .ex_table.pre before .ex_table, so the .ex_table.* wildcard
doesn't include the Pre-exception table.

Signed-off-by: Jason Andryuk <jason.andryuk@amd.com>
Reviewed-by: Alejandro Vallejo <alejandro.garciavallejo@amd.com>