armclang: disable all non Xilinx platforms
Work around an armclang bug:

  Error: L6242E: Cannot link object built_in.o as its attributes are incompatible with the image attributes.
  ... A64 clashes with SoftVFP.

See:

https://community.arm.com/developer/tools-software/tools/f/arm-compilers-forum/44287/arm-compiler-6-compiles-data-only-c-file-with-softvfp-attribute

Signed-off-by: Stefano Stabellini <stefano.stabellini@xilinx.com>