xen/virtio: Add DEVICE_TREE_PARSE dependency for VIRTIO_MMIO_NON_BLOCKING
dom_construct_virtio() lives in common/device-tree/virtio.c which is
only built when DEVICE_TREE_PARSE is enabled. On x86,
VIRTIO_MMIO_NON_BLOCKING can be enabled without DEVICE_TREE_PARSE,
causing the domain builder to reference an unbuilt symbol.

Add DEVICE_TREE_PARSE to the depends line.

Fixes linker error:
  undefined reference to `dom_construct_virtio'

Signed-off-by: Stefano Stabellini <stefano.stabellini@amd.com>
Reviewed-by: Michal Orzel <michal.orzel@amd.com>